app/urls.py
from django.contrib import admin
from django.urls import path
from .views import ProductFormView, ProductList

urlpatterns = [
        path("add_product/", ProductFormView.as_view(), name="ola"),
        path("", ProductList.as_view(), name ="lista"),
        ]

coffe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('app.urls')),
    path("Users/", include('usuarios.urls')),
    path("products/",include('orders.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path   
from . import views            

urlpatterns = [
        path("mi-orden/", views.MyOrderView.as_view(), name="my_order"),
        path("crear_orden/", views.CreateOrderProduct.as_view(), name="crear_orden"),
        ]

orders/models.py
from django.db import models
from app.models import Product #Se debe importar para los detalles de la orden.
from django.contrib.auth.models import User

# Create your models here.

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE) #Si el usuario desaparece se borra la orden 
    is_active = models.BooleanField(default=True) #Determina si la orden esta activa y no fue atendida
    order_date = models.DateTimeField(auto_now_add=True) #Se crea con la fecha actual

    #Le estamos agregando un formato a la forma en la que se va representar en el admin.
    def __str__(self):
        return f"order {self.id} by {self.user}"



#En esta clase se guardan todos los items de la orden.
class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE) #LLave foranea de Order
    product = models.ForeignKey(Product, on_delete=models.PROTECT) #Llave foranea de la clase products de la app principal (se importa) y en on_delete Protect para que no se borren los productos que ya estan en una orden 
    quantity = models.IntegerField() #Para la cantidad de productos elegida.


    def __str__(self) -> str:
        return f"{self.order} - {self.product}"

orders/forms.py
from django import forms
from .models import OrderProduct

class CreateOrderForm(forms.ModelForm):
    class Meta:
        model = OrderProduct
        fields = ['product'] 
       

orders/views.py
from django.shortcuts import render
from django.views.generic import DetailView, CreateView  #DetailView funciona si en la url le pasamos un argumento con el que pueda buscar esa orden.
from .models import Order, OrderProduct
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CreateOrderForm
from django.urls import reverse_lazy


#en este caso vamos a mostrar cada orden que este activa y no requiera un flag

# Create your views here.

#Vamos a organizar la vista generica para que no necesite el arhumento pasado por url
class MyOrderView(LoginRequiredMixin, DetailView):
    model = Order
    template_name = "my_order.html"
    context_object_name = 'order' #Con este contexto vamos a poder acceder desde el template


    #Sobreescribimos el metodo get_object para que en vez de recibir un parametro de la url, filtre por la flag definida en la db
    def get_object(self, queryset=None):
        return Order.objects.filter(is_active=True, user=self.request.user).first() #Filtra por ordenes activas y por usuario
    
    #Defino un contexto para pasar al template el cual define la pagina actual y sirve para mostrar el boton de mi pedido en función de si se esta en ella o no.
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_page'] = 'miorden'
        return context



#Creamos la vista para agregar poroductos a la orden o crar la orden, esta hereda de LoginRequeridMixin y CratedView
class CreateOrderProduct(LoginRequiredMixin, CreateView):
    #recivimos los parametros necesarios que requiere la vista.
    form_class = CreateOrderForm #Formulario
    template_name = 'create_order.html' # Template
    success_url = reverse_lazy('my_order') #Donde vamos a rediriir al user

    def form_valid(self, form): #Sobre escribimos el metodo form_valid
        order, _ = Order.objects.get_or_create( #Django nos permite obtener o crear esto es para que en caso de que la orden no este creada, se cree.(Camibia created por _ porque en este caso no se usa)
                is_active = True,
                user = self.request.user,
                ) #Los parametros que nesecitamos poner en la orden, activa y el usuario que la pide.
        
        form.instance.order = order #Asocia el producto que se está creando (representado por form.instance) con la orden obtenida o creada anteriormente.
        form.instance.quantity = 1 #Establece la cantidad del producto a 1. Esto podría ser configurable en el formulario, pero aquí se establece un valor por defecto.
        form.save() # Guarda los datos del formulario en la base de datos, creando un nuevo registro de producto asociado a la orden.
        return super().form_valid(form) #Llama al método form_valid de la clase base CreateView, que se encarga de la redirección a la URL de éxito definida anteriormente.
        #No se debe olvidar el return, si no la función no va a devolver nada.

orders/templates/create_order.html
{% extends 'base.html' %}


{% block content %}

    {% csrf_token %}
    {{ form.as_p }}
	<button type="submit"> Toca </button>


{% endblock %}

orders/templates/my_order.html
{% extends 'base.html' %}


{% block content %}

<div class="flow-root">
  <dl class="-my-3 divide-y divide-gray-100 text-sm">
    <div class="grid grid-cols-1 gap-1 py-3 sm:grid-cols-3 sm:gap-4">
      <dt class="font-medium text-gray-900">Usuario</dt>
      <dd class="text-gray-700 sm:col-span-2">{{order.user.username}}</dd>
    </div>

    <div class="grid grid-cols-1 gap-1 py-3 sm:grid-cols-3 sm:gap-4">
      <dt class="font-medium text-gray-900">Fecha</dt>
      <dd class="text-gray-700 sm:col-span-2">{{order.order_date|date}}</dd>
    </div>

{% for product_order in order.orderproduct_set.all %}

    <div class="grid grid-cols-1 gap-1 py-3 sm:grid-cols-3 sm:gap-4">
      <dt class="font-medium text-gray-900">Producto</dt>
      <dd class="text-gray-700 sm:col-span-2">{{ product_order.product.name }}</dd>
    </div>

    <div class="grid grid-cols-1 gap-1 py-3 sm:grid-cols-3 sm:gap-4">
      <dt class="font-medium text-gray-900">Precio</dt>
      <dd class="text-gray-700 sm:col-span-2">{{ product_order.product.price }}</dd>
    </div>

    <div class="grid grid-cols-1 gap-1 py-3 sm:grid-cols-3 sm:gap-4">
      <dt class="font-medium text-gray-900">Cantidad</dt>
      <dd class="text-gray-700 sm:col-span-2">{{ product_order.quantity }}</dd>
    </div>

    <div class="grid grid-cols-1 gap-1 py-3 sm:grid-cols-3 sm:gap-4">
      <dt class="font-medium text-gray-900">Descripción</dt>
      <dd class="text-gray-700 sm:col-span-2">
        {{ product_order.product.description }}
      </dd>
    </div>
  </dl>
</div>

{% empty %}

<h3> no hay items en la orede </h3>

{% endfor %}



{% endblock %}